[package]
name = "ceo"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ceo"
src = "src/main.rs"

[profile.release]
# Optimize for size
opt-level = 'z'
# LTO instructs the linker to optimize at the link stage. This can, for example, remove dead code and often times reduces binary size
lto = true
# By default, Cargo specifies 16 parallel codegen units for release builds. This improves compile times, but prevents some optimizations.
codegen-units = 1
# Automatically strip symbols from the binary.
# strip = true

[dependencies]
bytes = "1.6.0"
chrono = "0.4.38"
clap = { version = "4.5.4", features = ["derive"] }
figment = { version = "0.10.18", features = ["env", "yaml"] }
futures = "0.3.30"
http = "1.1.0"
itertools = "0.12.1"
minijinja = "2.0.1"
once_cell = "1.19.0"
regex = "1.10.4"
reqwest = { version = "0.12.4", features = ["stream", "rustls-tls"] }
scraper = "0.19.0"
serde = { version = "1.0.202", features = ["serde_derive"] }
serde_json = "1.0.117"
slack-morphism = { version = "2.2.0", features = ["hyper"] }
strum = { version = "0.26.2", features = ["derive"] }
text-to-ascii-art = "0.1.9"
tokio = { version = "1.37.0", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.10.2"
tokio-util = { version = "0.7.11", features = ["io"] }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
uuid = "1.8.0"
