[package]
name = "ceo-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# # Optimize for size
# opt-level = 'z'
# # LTO instructs the linker to optimize at the link stage. This can, for example, remove dead code and often times reduces binary size
# lto = true
# # By default, Cargo specifies 16 parallel codegen units for release builds. This improves compile times, but prevents some optimizations.
# codegen-units = 1
# # Automatically strip symbols from the binary.
# strip = true

[dependencies]
# again = "0.1.2"
bytes = "1.5.0"
chrono = "0.4.26"
##################################
# to be removed
cron = "0.12.0"
##################################
futures = "0.3.28"
http = "0.2.9"
itertools = "0.11.0"
minijinja = "1.0.8"
once_cell = "1.18.0"
reqwest = { version = "0.11.18", features = ["stream", "rustls-tls"] }
scraper = "0.17.1"
serde = { version = "1.0.185", features = ["serde_derive"] }
serde_json = "1.0.105"
slack-morphism = { version = "1.14.3", features = ["hyper"] }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
tokio-cron-scheduler = "0.9.4"
# tokio-stream = "0.1.14"
tokio-util = { version = "0.7.8", features = ["io"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
uuid = "1.4.1"
