[package]
name = "ceo-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.26"
reqwest = { version = "0.11.18" }
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
