[package]
name = "ceo-bot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# [profile.release]
# # Optimize for size
# opt-level = 'z'
# # LTO instructs the linker to optimize at the link stage. This can, for example, remove dead code and often times reduces binary size
# lto = true
# # By default, Cargo specifies 16 parallel codegen units for release builds. This improves compile times, but prevents some optimizations.
# codegen-units = 1
# # Automatically strip symbols from the binary.
# strip = true

[dependencies]
chrono = "0.4.26"
itertools = "0.11.0"
reqwest = { version = "0.11.18" }
serde = { version = "1.0.185", features = ["serde_derive"] }
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["macros", "rt-multi-thread"] }
